on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17, 23]

    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Check Java version
        run: java -version

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: mvn clean install

      - name: Check test coverage
        run: |
          coverage=$(mvn jacoco:report -q | grep -oP '.*coverage.*\K\d+')
          echo "Test coverage: $coverage"
          if [ "$coverage" -lt 80 ]; then
            echo "Test coverage below threshold. Failing build!"
            exit 1
          fi
