on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17, 23]

    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Check Java version
        run: java -version

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: mvn clean install

      - name: Generate JaCoCo report and capture coverage
        run: |
          mvn jacoco:report
          coverage=$(grep -oP '.*coverage.*\K\d+' target/site/jacoco/index.html)
          echo "Coverage: $coverage%"
          if [ "$coverage" -lt 80 ]; then
            echo "Code coverage is below threshold! Failing the build."
            exit 1
          fi
