on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
strategy:
  matrix:
    java: [11, 17, 23]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: mvn clean install
